services:
  slspanel:
    image: alexanderwagnerdev/slspanel:latest
    container_name: slspanel
     restart: unless-stopped
    environment:
      REACT_APP_BASE_URL: "${APP_URL}"
      REACT_APP_SRT_PLAYER_PORT: "${SRT_PLAYER_PORT:-4000}"
      REACT_APP_SRT_SENDER_PORT: "${SRT_SENDER_PORT:-4001}"
      REACT_APP_SLS_STATS_PORT: "${SLS_STATS_PORT:-8080}"
      REACT_APP_SRTLA_PORT: "${SRTLA_PORT:-5000}"
    ports:
      - "${SLS_MGNT_PORT}:8000"